### ISSUE TITLE
Does not compile with Kernel 4.5 (rc1)?

### ISSUE THREAD

**Issue by alexzeitgeist** [relan/exfat#25]
Tried to compile the latest git (Dec 19, 2015) with Kernel 4.5-rc1.

> DKMS make.log for exfat-1.2.9+20151110 for kernel 4.5.0-040500rc1-generic (x86_64)
Fri Jan 29 19:12:27 CET 2016
make: Entering directory '/usr/src/linux-headers-4.5.0-040500rc1-generic'
  LD      /var/lib/dkms/exfat/1.2.9+20151110/build/built-in.o
  CC [M]  /var/lib/dkms/exfat/1.2.9+20151110/build/exfat_core.o
  CC [M]  /var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.o
/var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.c:1379:2: error: unknown field ‘follow_link’ specified in initializer
  .follow_link = exfat_follow_link,
  ^
/var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.c:1379:17: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .follow_link = exfat_follow_link,
                 ^
/var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.c:1379:17: note: (near initialization for ‘exfat_symlink_inode_operations.create’)
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.o' failed
make[1]: *** [/var/lib/dkms/exfat/1.2.9+20151110/build/exfat_super.o] Error 1
Makefile:1391: recipe for target '_module_/var/lib/dkms/exfat/1.2.9+20151110/build' failed
make: *** [_module_/var/lib/dkms/exfat/1.2.9+20151110/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.5.0-040500rc1-generic'

**Comment by relan** [comment]
Wrong project. :) This exFAT implementation does not have a kernel module.  BTW this case perfectly illustrates the strong side of FUSE-based file systems.

**Comment by alexzeitgeist** [comment]
Ouch! My apologies. Shouldn't post to Github past midnight. :p
